name: fuel-prices

services:
  db:
    image: postgres:15
    restart: unless-stopped
    command: postgres -c shared_buffers=2GB
    environment:
      POSTGRES_USER:     ${DATABASE_USERNAME:-}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-}
      POSTGRES_DB:       fuel-prices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 1gb

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
