"""Add tables for price and station history

Revision ID: 041d080ed120
Revises: 1330438ba9f6
Create Date: 2026-06-29 23:10:55.211395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041d080ed120'
down_revision: Union[str, Sequence[str], None] = '1330438ba9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_description', sa.String(length=50), nullable=False),
    sa.Column('self_service', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('extraction_date', sa.Date(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=True),
    sa.Column('station_type', sa.String(length=20), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('brand_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('comune', sa.String(length=50), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('extraction_date', sa.Date(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
