"""Add parser error table

Revision ID: 562a313dd9fb
Revises: c0a87d94d8b9
Create Date: 2026-07-04 23:19:32.116987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562a313dd9fb'
down_revision: Union[str, Sequence[str], None] = 'c0a87d94d8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parser_error',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], name='fk_parser_error_file_id'),
    sa.PrimaryKeyConstraint('file_id', 'line_number')
    )
    op.create_index('idx_parser_error_file_id', 'parser_error', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parser_error_file_id', table_name='parser_error')
    op.drop_table('parser_error')
    # ### end Alembic commands ###
