"""Add file type column

Revision ID: 9ffb438ca31b
Revises: 562a313dd9fb
Create Date: 2026-07-06 15:30:49.139401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffb438ca31b'
down_revision: Union[str, Sequence[str], None] = '562a313dd9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    file_type_enum =sa.Enum('PRICES', 'STATIONS', name='file_type')
    file_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('file', sa.Column('file_type', file_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_type')

    sa.Enum(name='file_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
