"""Add foreign keys on file_id

Revision ID: c0a87d94d8b9
Revises: 687a696385f4
Create Date: 2026-07-04 21:41:25.687970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a87d94d8b9'
down_revision: Union[str, Sequence[str], None] = '687a696385f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_price_history_file_id', 'price_history', 'file', ['file_id'], ['file_id'])
    op.create_foreign_key('fk_station_history_file_id', 'station_history', 'file', ['file_id'], ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_station_history_file_id', 'station_history', type_='foreignkey')
    op.drop_constraint('fk_price_history_file_id', 'price_history', type_='foreignkey')
    # ### end Alembic commands ###
